knpu_oauth2_client:
    clients:
        # configure your clients as described here: https://github.com/knpuniversity/oauth2-client-bundle#configuration
        google:
            type: google
            client_id: '%env(GOOGLE_CLIENT_ID)%'
            client_secret: '%env(GOOGLE_CLIENT_SECRET)%'
            redirect_route: google_check
            redirect_params:
                service: 'google'
            #redirect_params: { scope: 'userinfo.email' }
            # if you want to use the "offline" mode, uncomment the following line:
            access_type: "offline"
            user_fields: [email, password]

        