controllers:
    resource:
        path: ../src/UserInterface/Controller/
        namespace: RightSide\Controller
    type: attribute


# This file is the entry point to configure your own routes.

cv_elhadi:
    path: /
    # the controller value has the format 'controller_class::method_name'
    controller: RightSide\Controller\ElhadiController
cv_analytics:
    path: /analytics
    # the controller value has the format 'controller_class::method_name'
    controller: RightSide\Controller\AnalyticsController
    # if the action is implemented as the __invoke() method of the
    # controller class, you can skip the '::method_name' part:
    # controller: App\Controller\BlogController


google_connect:
    path: /connect/google
    controller: RightSide\Controller\GoogleController

google_check:
    path: /connect/google/check
    controller: RightSide\Controller\SocialeController

google_disconnect:
    path: /disconnect/google
    controller: RightSide\Controller\GoogleController::logout

cv_register:
    path: /register
    controller: RightSide\Controller\RegistrationController::register
     
cv_verify_email:
    path: /verify/email
    controller: RightSide\Controller\RegistrationController::verifyUserEmail

cv_logout:
    path: /logout
    controller: RightSide\Controller\SecurityController::logout