controllers:
    resource:
        path: ../src/UserInterface/Controller/
        namespace: App\Controller
    type: attribute


# This file is the entry point to configure your own routes.

cv_elhadi:
    path: /
    # the controller value has the format 'controller_class::method_name'
    controller: App\UserInterface\Controller\ElhadiController
cv_analytics:
    path: /analytics
    # the controller value has the format 'controller_class::method_name'
    controller: App\UserInterface\Controller\AnalyticsController
    # if the action is implemented as the __invoke() method of the
    # controller class, you can skip the '::method_name' part:
    # controller: App\Controller\BlogController