controllers:
    resource:
        path: ../src/UserInterface/Controller/
        namespace: RightSide\Controller
    type: attribute


# This file is the entry point to configure your own routes.

cv_elhadi:
    path: /
    controller: RightSide\Controller\ElhadiController

cv_analytics:
    path: /analytics
    controller: RightSide\Controller\AnalyticsController

cv_login:
    path: /login
    controller: RightSide\Controller\GoogleController::login

google_connect:
    path: /connect/{service}
    controller: RightSide\Controller\GoogleController::connectAction
    methods: GET

google_check:
    path: /connect/check/{service}
    controller: RightSide\Controller\GoogleController::connectCheckAction
    methods: ['GET', 'POST']

google_disconnect:
    path: /disconnect/google
    controller: RightSide\Controller\GoogleController::logout

cv_register:
    path: /register
    controller: RightSide\Controller\RegistrationController::register
     
cv_verify_email:
    path: /verify/email
    controller: RightSide\Controller\RegistrationController::verifyUserEmail

cv_logout:
    path: /logout
    controller: RightSide\Controller\SecurityController::logout

login_success:
    path: /login/success
    controller: RightSide\Controller\SecurityController::loginSuccess

cv_social_connect:
    path: /social/connect
    controller: RightSide\Controller\SocialeController